name: stereo98
description: Stereo 98 DAB+ Radio Streaming

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=3.5.0 <4.4.0"
  flutter: ">=3.24.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  get: 4.7.3
  get_storage: 2.1.1
  flutter_screenutil: 5.9.3
  google_fonts: 7.1.0
  just_audio: ^0.9.42
  audio_service: ^0.18.15
  audio_session: ^0.1.21
  animate_icons: ^2.0.0
  url_launcher: 6.3.2
  glassmorphism: ^3.0.0
  rating_dialog: ^2.0.4
  store_redirect: 2.0.4
  dynamic_themes: ^1.1.0
  http: 1.6.0
  shimmer: ^3.0.0
  permission_handler: ^12.0.1
  connectivity_plus: ^7.0.0
  dropdown_button2: ^2.3.9
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  path_provider_android: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
